generate report

diff --git a/.github/workflows/build_and_test.yml b/.github/workflows/build_and_test.yml
--- a/.github/workflows/build_and_test.yml
+++ b/.github/workflows/build_and_test.yml
@@ -25,4 +25,11 @@ jobs:
     - name: Build
       run: dotnet build --no-restore
     - name: Test
-      run: dotnet test --no-build --verbosity normal --logger:"trx;LogFileName=/test-results.xml"
+      run: dotnet test --no-build --logger "trx;LogFileName=reports/test-results.trx"
+    - name: TestReport
+      uses: dorny/test-reporter@v2
+      if: success() || failure()    # run this step even if previous step failed
+      with:
+        name: NUnit Tests           # Name of the check run which will be created
+        path: reports/jest-*.trx    # Path to test results
+        reporter: dotnet-trx        # Format of test results
